-- Intentionally left as a no-op.
--
-- This migration was generated before the `SelfEnrollmentRequest` table-creation
-- migration, which caused fresh replays into Prisma's shadow database to fail.
-- The actual enum/status conversion now lives in a later migration that runs
-- after the table exists.
